name: CI

on: [pull_request]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.x

    - name: Echo versions used
      run: echo "node:" && node --version && echo "" && echo "npm:" && npm --version && echo "" && echo "yarn:" && yarn --version

    - name: Install dependencies
      run: yarn install

    - name: Run CI script
      run: yarn run ci

    - name: Deploy
      if: github.event_name == 'pull_request' && github.ref != 'refs/heads/master'
      run: npx netlify-cli@^2 deploy --dir=./public
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
