name: CI

on: push

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.x

    - name: Echo versions used
      run: echo "node:" && node --version && echo "" && echo "npm:" && npm --version && echo "" && echo "yarn:" && yarn --version

    - name: Install dependencies
      run: yarn install

    - name: Run CI script
      run: yarn run ci

    - name: Run CI script
      run: yarn run build
      
    - name: Netlify Deploy
      uses: nwtgck/actions-netlify@v1.1.0
      with:
        publish-dir: public
        github-token: ${{ secrets.GITHUB_TOKEN }}
        production-branch: master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
